name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'studyNote-site/**'
      - 'studyNote/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Change to studyNote-site directory
        run: cd studyNote-site

      - name: Build
        run: |
          cd studyNote-site
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./studyNote-site/public
          publish_branch: gh-pages
