version: '3'

services:
  rstudio:
    image: rocker/rstudio
    container_name: rstudio
    ports:
      - 8787:8787
    environment:
      PASSWORD: rstudio
      TZ: Asia/Tokyo
    volumes:
      - ./R:/home/rstudio
