version: '3'

services:
  rstudio:
    build:
      dockerfile: Dockerfile
    container_name: rstudio
    ports:
      - 8787:8787
    environment:
      PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ./R:/home/rstudio
