baseURL = "https://useakat.github.io/RNAseqAnalysis/studyNote-site/"
languageCode = "ja"
title = "Study Notes"
theme = "docsy"

# Hugo module configuration
[module]
  [module.hugoVersion]
    extended = true
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

# Language settings
defaultContentLanguage = "ja"
[languages]
[languages.ja]
title = "Study Notes"
description = "Study Notes Documentation"
languageName = "日本語"
weight = 1

# Docsy theme settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Enable syntax highlighting
[markup.highlight]
style = "monokai"

# Navigation
[menu]
[[menu.main]]
    name = "Home"
    weight = 10
    url = "/"

[params]
copyright = "Yoshitaro Takaesu"
privacy_policy = "https://policies.google.com/privacy"

# Enable search
[outputs]
home = [ "HTML", "RSS", "JSON" ]
