baseURL = "https://useakat.github.io/RNAseqAnalysis"
title = "RNAseq Analysis"
theme = ["docsy"]

# Language settings
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false  # Changed to true to ensure proper path handling
languageCode = "ja"

# Disable git info
enableGitInfo = false

[languages]
  [languages.ja]
    title = "RNAseq Analysis"
    languageName = "Japanese"
    weight = 1
    contentDir = "content"  # Explicitly specify content directory
    [languages.ja.params]
      time_format_default = "2006-01-02"

[menu]
  [[menu.main]]
    name = "Home"
    weight = 1
    url = "/"  # Updated to include language prefix
  [[menu.main]]
    name = "Documents"
    weight = 2
    url = "/docs/"  # Updated to include language prefix
  [[menu.main]]
    name = "Quantification"
    weight = 3
    url = "/docs/quantifying/"  # Updated to include language prefix
  [[menu.main]]
    name = "Indexing"
    weight = 4
    url = "/docs/indexing/"  # Updated to include language prefix

[params]
copyright = "Yoshitaro Takaesu"
# Repository configuration
github_repo = "https://github.com/useakat/RNAseqAnalysis"
github_branch = "main"

# Docsy theme params
[params.ui]
sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_cache_limit = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
section = [ "HTML", "RSS" ]

# Hugo module configuration
[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

# Explicitly define section types
[taxonomies]
  tag = "tags"
  category = "categories"

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.JSON]
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

# Ensure all static files are copied to the language directory
[build]
  writeStats = true
