baseURL = "/ja/"
title = "Study Notes"
theme = ["docsy"]

# Language settings
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true

# Disable git info
enableGitInfo = false

[languages]
  [languages.ja]
    title = "Study Notes"
    languageName = "日本語"
    weight = 1
    contentDir = "content/ja"
    [languages.ja.params]
      time_format_default = "2006-01-02"

[menu]
  [[menu.main]]
    name = "ホーム"
    weight = 1
    url = "/"
  [[menu.main]]
    name = "ドキュメント"
    weight = 2
    url = "/docs/"
  [[menu.main]]
    name = "定量化"
    weight = 3
    url = "/docs/quantifying/"
  [[menu.main]]
    name = "インデックス構築"
    weight = 4
    url = "/docs/indexing/"

[params]
copyright = "Yoshitaro Takaesu"
# Repository configuration
github_repo = "https://github.com/useakat/RNAseqAnalysis"
github_branch = "main"

# Docsy theme params
[params.ui]
sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_cache_limit = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
section = [ "HTML", "RSS" ]

# Hugo module configuration
[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

# Explicitly define section types
[taxonomies]
  tag = "tags"
  category = "categories"

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.JSON]
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

# Ensure all static files are copied to the language directory
[build]
  writeStats = true

# Copy static files to language subdirectory
[[deployment]]
  target = "public/ja"
  [[deployment.matchers]]
    pattern = "^.+\\.(js|css|svg|ttf|eot|woff2?)$"
    gzip = true
